// components/organisms/header.tsx
import ChangeThemeButton from "@/components/molecules/changeThemeButton";
import Link from "next/link";

function Header(): JSX.Element {
  return (
    <header className="flex flex-wrap overflow-auto justify-between items-center content-center w-full px-3 py-2 lg:px-5 lg:py-3 mb-2 sticky top-0 select-none shadow-2xl bg-gray-100 dark:bg-black-800 z-50">
      <nav>
        <ul className="flex flex-wrap font-medium text-gray-600 dark:text-gray-300">
          <li className="pr-2 hover:text-blue-400 transition duration-200 ease-in-out">
            <Link href="/">
              <a>Home</a>
            </Link>
          </li>
          <li className="pr-2 hover:text-blue-400 transition duration-200 ease-in-out">
            <Link href="/projects">
              <a>Projects</a>
            </Link>
          </li>
          <li className="pr-2 hover:text-blue-400 transition duration-200 ease-in-out">
            <Link href="/blog">
              <a>Blog</a>
            </Link>
          </li>
        </ul>
      </nav>
      <ChangeThemeButton />
    </header>
  );
}

export default Header;

// src/components/Header.vue
<template>
  <header class="header">
    <nav class="header__nav">
      <ul class="header__items">
        <li class="header__item">
          <router-link to="/" title="Home">Home</router-link>
        </li>
        <li class="header__item">
          <router-link to="/" title="Projects">Projects</router-link>
        </li>
        <li class="header__item">
          <router-link to="/" title="Blog">Blog</router-link>
        </li>
      </ul>
    </nav>
  </header>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Header",
});
</script>

<style lang="scss" scoped>
@import "~@/scss/_variables.scss", "~@/scss/_breakpoints.scss";

.header {
  display: flex;
  align-items: center;
  width: 100%;
  box-shadow: 2px 2px 40px 20px $color-bluegray-100;
  position: sticky;
  top: 0;
  user-select: none;
  padding: 0.8rem 2rem;
  background-color: #fcfcfc;
  @include breakpoints(lg) {
    padding: 1.2rem 2rem;
  }

  .header__items {
    display: flex;
    justify-content: center;
    align-items: center;
    margin: 0;
    padding: 0;

    .header__item {
      margin-right: 1rem;
      list-style: none;

      a {
        text-decoration: none;
        color: $color-bluegray-500;
        font-weight: 500;

        &:hover {
          color: $color-blue-500;
          transition: color 0.3s ease-in-out;
        }
      }
    }
  }
}
</style>
