// components/Navigation.vue
<template>
  <v-app-bar dense app color="back_dark">
    <v-spacer />
    <v-btn text color="primary" href="/">Home</v-btn>
    <v-btn text color="primary" href="/projects">Projects</v-btn>
    <v-btn text color="primary" href="/blog">Blog</v-btn>
    <v-btn text color="primary" href="/about">About</v-btn>
    <v-spacer />
  </v-app-bar>
</template>

// src/components/navigation.tsx
import React from "react";
import Link from "next/link";

class Navigation extends React.Component {
  render() {
    return (
      <nav className="nav_containner">
        <ul>
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/projects">Projects</Link>
          </li>
          <li>
            <Link href="/blog">Blog</Link>
          </li>
          <li>
            <Link href="/about">About</Link>
          </li>
        </ul>
      </nav>
    );
  }
}

export default Navigation;
